### ISSUE TITLE
wrong infinity edge

### ISSUE THREAD

**Issue by d4nlo3008** [Just2good/TFT-Overlay#102]
please fix the description of the infinity edge:

its +150% dmg and not 100% like in the 2.0.3. version. 

greetings

**Comment by xadamxk** [comment]
Based on the commit history, none of the changes in the most recent version have been added to the overlay. Give the developer a bit to update it since it's only been a couple days.

**Comment by Just2good** [comment]
Adding in 9.15 changes right now
