### ISSUE TITLE
Overlay not working

### ISSUE THREAD

**Issue by PoweredDragon** [Just2good/TFT-Overlay#110]
After update 2 before last update, the overlay stopped working completely. I thought it's some bug to be fixed, but it still doesn't work. It's in my antivirus exceptions, i can't turn it on even using cmd or powershell (ofc with admin mode). It just doesn't pop up - no task is started (or I can't find any task associated with it), not a single process. :(

EDIT:
Windows 10, Home Ed. Never had problems with overlay before the "autoupdater hotfix"

**Comment by Just2good** [comment]
Are you using 2.0.4?

**Comment by PoweredDragon** [comment]
yep

**Comment by Just2good** [comment]
Odd, mine works completely fine, try redownloading it and see what happens

**Comment by PoweredDragon** [comment]
Tried it; nothing works. Just the older versions which aren't really useful.
Guess I'll learn to live without it

**Comment by PoweredDragon** [comment]
Been there, done that; didn't work. Are you sure there was nothing added that might have needed any special exception?

Guess I'm gonna need to learn living without it :D

**Comment by Just2good** [comment]
Okay so it doesn't even appear in task manager at all? Add me on discord(In the readme) I can prob do live fix compiles to see what exactly is causing your issue. *Edit* Asked a few others on discord if they have issues and they have been using it just fine apparently
