### ISSUE TITLE
This's maybe UI bug?

### ISSUE THREAD

**Issue by SuTree** [Just2good/TFT-Overlay#128]
Hi, See the pic

![20191009162419](https://user-images.githubusercontent.com/7479059/66464288-463ca000-eab1-11e9-9d59-4b8b66885757.png)

**Comment by 1055169799** [comment]
是的，我也看到这个了，但是这个软件新的开发者的主页并没有问题提交的页面，不知道在这里发出提问他能否看得见。
Yes, I also saw this, but the new developer's homepage of this software has no problem to submit the page, I don't know if he can ask questions here.

**Comment by SuTree** [comment]
我想可以的。

I think It's OK.

**Comment by jtborn** [comment]
Yeah, unfortunately I can't get an Issues page unless github disconnects my repo from the original dev. I may ask them to do that since he's not updating it anymore. I see the bug you're talking about and I'll fix it in my version.

**Comment by jtborn** [comment]
![image](https://user-images.githubusercontent.com/5599010/66877314-d8d5b700-ef69-11e9-91b1-ff0bd75f5670.png)

Fixed, thanks. Credited in the readme
https://github.com/jtborn/TFT-Overlay/releases/tag/V2.1.6

**Comment by 1055169799** [comment]
> ![图片](https://user-images.githubusercontent.com/5599010/66877314-d8d5b700-ef69-11e9-91b1-ff0bd75f5670.png)
> 
> 固定，谢谢。归功于自述文件
> https://github.com/jtborn/TFT-Overlay/releases/tag/V2.1.6

Great, brother, love you.
太好了，兄弟，爱你。
I will let my friends use it right away.
我马上让我的小伙伴们用上它。

**Comment by SuTree** [comment]
@jtborn thanks.
