### ISSUE TITLE
Bit defender identified TFT Overlay.exe as malware

### ISSUE THREAD

**Issue by MantasS0** [Just2good/TFT-Overlay#13]
Bit defender identified TFT Overlay.exe as malware. This has occurred only on this commit.
I have the 06.30 commit in a separate folder without any issues. 
![tft malware 1](https://user-images.githubusercontent.com/44400644/60519146-9acec300-9ceb-11e9-8246-d398edf85a7c.JPG)
![tft malware 2](https://user-images.githubusercontent.com/44400644/60519147-9acec300-9ceb-11e9-80e9-f44b47550391.JPG)

**Comment by Just2good** [comment]
False positive, may need to add to exceptions. If you look at my recent commits, I added something called MVVM. That allows me to call code from a different project file and makes MainWindow less cluttered. 
See Resource folder.

**Comment by MantasS0** [comment]
I see. Thank you for the clarification. :)
