### ISSUE TITLE
Scale option.

### ISSUE THREAD

**Issue by Hiffix** [Just2good/TFT-Overlay#15]
I play on laptop even whit 1080p i dont see full list of classes/origins. 
Or i can somehow make font smaller so all gonna fit?

**Comment by Just2good** [comment]
1920x1080? If so then it should fit just fine.
What version are you using? And have you tried moving the bar around by dragging the orange rectangle?

**Comment by Hiffix** [comment]
17.3" Full HD (1920x1080) even whit max corner position it not fit. Last version ofcoz 1.7

**Comment by Just2good** [comment]
Maybe the laptop monitor is small. Hmm.

Resizing is low priority atm, but I will be changing classes/origins so they should fit your screen when that happens. I will see if I can do a quick resize fix anyway though. Thanks for letting me know!

**Comment by Just2good** [comment]
Resizing added to newest release
