### ISSUE TITLE
AutoUpdater for all the constant changes?

### ISSUE THREAD

**Issue by novatorem** [Just2good/TFT-Overlay#16]
The game is getting patches very often, and you (and the other contributors) are always updating the codebase + adding new features. An autoupdater would be nice if you can pull from somewhere. I can look into it soon and submit a pull request if it works out, but haven't tried anything like it yet.

**Comment by Just2good** [comment]
Never made an autoupdater before, does sound really nice though.

**Comment by novatorem** [comment]
Don't know any C# so this'll take a while in the making. If anyone has better ideas or wants to pick it up, let me know.

1. Use a [webscraper](https://ironsoftware.com/csharp/webscraper/) on [Pulse](https://github.com/Just2good/TFT-Overlay/pulse) to get the latest version. 

2. Run a command on launch to compare the versions, if a newer one is out, [download the .zip and replace the existing one](https://social.msdn.microsoft.com/Forums/SqlServer/en-US/63d651f2-fba6-4c46-afb1-f046847a9a3d/c-zip-file-extract-and-overwrite?forum=csharpgeneral).

For anyone who knows more C#, are there any issues with this flow? Assuming you can download from a link, and restart with the newer .exe?

The only issues I can think of is it might get picked up by an AntiVirus. The plus side is there won't be a need for server-side coding/hosting.

**Comment by novatorem** [comment]
Commit f30a5c6 begins this, can safely be closed.
