### ISSUE TITLE
Overlay Bugsplat

### ISSUE THREAD

**Issue by xadamxk** [Just2good/TFT-Overlay#19]
Has anyone ran into the issue of league throwing an error, which terminates the game, and says you need to disable any overlays you have running?

EDIT: It happened to me twice for the first time in my last game. I restarted the client and it hasn't happened since though.

**Comment by Just2good** [comment]
Hmm I haven't played TFT in awhile, but definitely tell me if this happens again!

**Comment by Just2good** [comment]
Just played a match and no bugsplat error, do you have any other overlays that hook to the client? Like discord or something?

**Comment by xadamxk** [comment]
I do not. It only happened one game and hasn't since then. If I can figure out how to replicate it, I'll reopen this and let you know.
