### ISSUE TITLE
Tabs impacts usability

### ISSUE THREAD

**Issue by eerilai** [Just2good/TFT-Overlay#22]
I like the design but I really liked not having to click on the overlay to see things, which causes my game to lose focus, which tanks the FPS and causes some stuttering. I also just liked the overall quick accessibility of all the charts (not having to click anything regardless of performance impact). Could grouping things under tabs be optional? At least maybe for Items+Origins+Info Charts. Champions may not work all under one tab depending on what's planned for that but everything else shouldn't take up too much space.

**Comment by Just2good** [comment]
This was a test run to see how many people liked the tabs. Due to all the feedback so far, I may put all the buttons into the same tab, and have new features in different tabs.

**Comment by ghost** [comment]
I agree. 
I understand what you tried to do, but having to click on the overlay really ruins the functionality.
Anyways, thanks for sharing your work. For now i'll keep using the 1.7.2 version, wich i love!
Greetings

**Comment by Just2good** [comment]
Newest version has it back to the one bar theme, let me know what you think.

**Comment by eerilai** [comment]
Awesome! Looks great. Thanks for your response and quick implementation. Looking forward to further features. 
Closing this issue.
