### ISSUE TITLE
Not saving preferences

### ISSUE THREAD

**Issue by foliveira15** [Just2good/TFT-Overlay#28]
Hello
Preferences like Size, Position, Transparency, Auto-update, etc, are not been saved.
Every time I reopen the app, all options are back to default. Really annoying.
Tested on 1.8.2

**Comment by Just2good** [comment]
Yep someone mentioned this to me earlier today, going to add this in when I can

**Comment by Just2good** [comment]
Size, Position, Lock, Always On Top preference saving added in new update.
