### ISSUE TITLE
Height adjustment for the grid in Origins

### ISSUE THREAD

**Issue by kllin3** [Just2good/TFT-Overlay#40]
Some descriptions in Origins are covered, like the Demons in the picture down below.
![report](https://user-images.githubusercontent.com/30870594/60945998-aa6b8e80-a31f-11e9-8f2a-851ef296fe74.JPG)

P.S. Thank you for this useful tool! If you want to add the translation for Origins and Classes, I would like to help to translate into zh-TW :)

**Comment by Just2good** [comment]
I can't seem to replicate this, what version are you using? The current version is [1.9](https://github.com/Just2good/TFT-Overlay/releases) and it has zh-TW translations.

**Comment by kllin3** [comment]
Ver. 1.9. There are only item translations, but Origins and Classes are still in English.

**Comment by Just2good** [comment]
Yeah there is no template for Origins/Classes yet, its only items. Can you tell me how you got it cut off like that?

**Comment by kllin3** [comment]
Just open the app though. Either point on the icon of origins or click it would show this.
![report2](https://user-images.githubusercontent.com/30870594/60950860-895c6b00-a32a-11e9-9f4e-c34f70d23933.JPG)

**Comment by kllin3** [comment]
I would try on different computer later to see if this happens as well.

**Comment by Just2good** [comment]
Odd, it doesnt do this for me at all

**Comment by kllin3** [comment]
Same situation on my another PC with ver. 1.9.1. I have no idea what the reason is. (maybe font type... IDK) 
If no one reports this as well until tomorrow, I may close this issue because it means most users do not confront this problem.

 And again, if you want to add translation for origins/classes, I would like to help at any time :)

**Comment by LazyZhu** [comment]
Win10 x64, TFT-Overlay v1.91, same Origins issue here:
![01](https://user-images.githubusercontent.com/2244967/61013141-0f70c400-a3b4-11e9-8bcb-33391483717f.png)
But Classes are fine:
![02](https://user-images.githubusercontent.com/2244967/61013170-2ca59280-a3b4-11e9-9b17-b3018bbffbf9.png)

**Comment by yunchi0921** [comment]
same issue
![擷取](https://user-images.githubusercontent.com/29368331/61014575-c1ab8a00-a3ba-11e9-8487-be72fc504764.PNG)

**Comment by Just2good** [comment]
Okay, I'll see if I can fix this in the next release

**Comment by Just2good** [comment]
New version is out, let me know if this fixed the issue or not please.

**Comment by yunchi0921** [comment]
![擷取](https://user-images.githubusercontent.com/29368331/61021865-e103e080-a3d5-11e9-81d6-3ccf979794e4.PNG)

it works!

**Comment by Just2good** [comment]
Awesome, closing
