### ISSUE TITLE
Overlay.exe

### ISSUE THREAD

**Issue by ge36rax** [Just2good/TFT-Overlay#46]
Cant find the Overlay.exe after extracting...

**Comment by hignz** [comment]
https://github.com/Just2good/TFT-Overlay/releases/download/V1.9.1/TFT.Overlay.V1.9.1.rar

![image](https://user-images.githubusercontent.com/20867442/61009379-65207e80-a36a-11e9-9419-016ad09c49f3.png)

**Comment by Just2good** [comment]
If you still don't see it, try adding it to exceptions on your AV/Windows Defender
