### ISSUE TITLE
Issue: Can't see program when in-game

### ISSUE THREAD

**Issue by Elvizzzz22** [Just2good/TFT-Overlay#50]
When I open program, and then launch LoL, I can't see program in-game. So I need to alt-tab to actually see the program.

**Comment by xadamxk** [comment]
Are you playing League in full-screen mode? If so, try changing the video setting to windowed or borderless mode. This overlay program can't overlay league while in fullscreen.

**Comment by Just2good** [comment]
Exactly what xadamxk said, fullscreen does not work for this overlay and fixing that issue would require hooking to the LoL client itself which I am not fond of.
