### ISSUE TITLE
这个阵容和搭配那边能弄中文麽

### ISSUE THREAD

**Issue by JunLock** [Just2good/TFT-Overlay#57]

**Comment by KKaKa** [comment]
中文已经支持了 在橙色右键选择

**Comment by iblh** [comment]
> 中文已经支持了 在橙色右键选择

只有装备有翻译，而且我更换了其他不同语言发现羁绊都没有翻译效果。虽然已经有了翻译文本，但是不知为何效果没出来。

**Comment by XHC-1996** [comment]
为什么我运行软件没有反应呢？ 有人和我一样的情况吗？

**Comment by FreeGoStudio** [comment]
更新到1.96版,我就记得我明明提取了羁绊并且汉化了,我还以为汉化失效了

**Comment by izoyo** [comment]
> 更新到1.96版,我就记得我明明提取了羁绊并且汉化了,我还以为汉化失效了

作者没发布新的Release

**Comment by izoyo** [comment]
我自己汉化了一遍

https://github.com/izoyo/TFT-Overlay/releases

**Comment by FreeGoStudio** [comment]
> > 更新到1.96版，我就记得我明明提取了羁绊并且汉化了，我还以为汉化失效了
> 
> 作者没发布新的版本

昨天就发布了1.96版,这个问题可以关闭了

**Comment by Just2good** [comment]
Hello I dont really know chinese, but right now releases are slow because I'm trying to fix/add multiple things at once on my test project. Chinese translation was added recently #72. 谢谢
