### ISSUE TITLE
Offer compiled .zip folder alongside .rar

### ISSUE THREAD

**Issue by AshGrowem** [Just2good/TFT-Overlay#58]
This would greatly increase ease of use for people too lazy or technically disabled to figure out extracting `.rar` files. Thanks!

**Comment by xadamxk** [comment]
Why can't windows extract rar's natively anyways? I'm all for this idea. For a while, ZIPs were offered on releases.

**Comment by Just2good** [comment]
Will do, might just make the default a .zip since it is making it unnecessarily harder. (Too many people asking me how to open .rar)
