### ISSUE TITLE
Recent Design Changes & QOL Suggestion

### ISSUE THREAD

**Issue by xadamxk** [Just2good/TFT-Overlay#59]
I love the recent changes. Adding a new tab for the possible items was a great addition.

With that being said, I do have a QOL request. Would it be possible for the opacity slider to also affect the icons on the possible items tool, that way I don't have to switch to the main tab for the grid overlay to stop covering a good portion of the game? I play on a single monitor usually so moving the overlay isn't much of an option.

Cheers.

**Comment by hignz** [comment]
I like this suggestion. Although I think there should be an icon opacity setting, independent of the background opacity. 

I have it implemented on my local build but ultimately it is up to Just2good.

**Comment by xadamxk** [comment]
Can you make a PR for it and attach it to this issue for me so the dev is more likely to implement it? That would be awesome. Thank you.

**Comment by hignz** [comment]
Sorry for the delay. I will make a PR later. 

In the time being you can check out the changes on my fork.

**Comment by Just2good** [comment]
Feel free to make a PR hignz. Also I'm removing that space of item icons that aren't being used.

**Comment by Just2good** [comment]
Most likely going to make the opacity buttons for the actual item icons only
