### ISSUE TITLE
Try to run TFT overlay.exe, but nothing shows up.

### ISSUE THREAD

**Issue by XHC-1996** [Just2good/TFT-Overlay#68]
I try to run TFT overlay.exe, but nothing shows up.

**Comment by foliveira15** [comment]
Same here

**Comment by Just2good** [comment]
Honestly every old version stopped working and I'm not sure why. Try downloading this [Pre-Release](https://github.com/Just2good/TFT-Overlay/releases/tag/V1.9.6) and let me know if it works.

**Comment by foliveira15** [comment]
Pre-release working fine. 1.9.5 was with auto-update enabled

**Comment by Just2good** [comment]
Auto-update is also in 1.9.6

**Comment by foliveira15** [comment]
> Auto-update is also in 1.9.6

Yeah I know, but old versions stopped working when the update was enabled

**Comment by Just2good** [comment]
Figured out the main issue and its about to be fixed right now
