### ISSUE TITLE
apply for authorization

### ISSUE THREAD

**Issue by bai-rookie** [Just2good/TFT-Overlay#70]
dear Just2good,

i am  a chinese TFT player. your programme TFT-Overlay is so helpful to me. And i believe that other chinese players have the same thought as me. So i want to spread this useful tool on the chinese TFT forum or community. Therefore i want to get your authorization.

Sincerely,
bai-rookie.

**Comment by Just2good** [comment]
Yep if you want to tell other people feel free to do so, dont need to ask.
