### ISSUE TITLE
Suggestion: User Interface of item builder

### ISSUE THREAD

**Issue by LazyZhu** [Just2good/TFT-Overlay#76]
1. Item builder can add/remove base items by left/right click their icons, then no need + and - buttons anymore.
2. We can click combined item icons to remove base items that already combined
3. Add tooltips to the all items.
4. With 1, 2 and 3 achieved, now can merge main menu item builder together.

**Comment by LazyZhu** [comment]
Looks like this:
![20190717164358](https://user-images.githubusercontent.com/2244967/61362446-cab5c300-a8b4-11e9-9553-b0903f53b738.png)

**Comment by Just2good** [comment]
I'll keep this open for future reference

**Comment by xadamxk** [comment]
Props to @LazyZhu for this suggestion. I think it is brilliant to remove the +/- UI and use the existing UI to manage the potential item builds. While also removing the duplicated items from the bottom left half of the table. I would love to see this implemented.

**Comment by LazyZhu** [comment]
@Just2good 
I find an item builder the way works mostly like i suggested, but it's a website version.
http://tft-cheatsheet.com/
It's Origin & Class table also looks better.

**Comment by Just2good** [comment]
I'll see if I can implement this, its definitely much easier to do this on a website (imo). But I'll see what I can do. Will comment again when done.
