### ISSUE TITLE
Stop working

### ISSUE THREAD

**Issue by weblll** [Just2good/TFT-Overlay#85]
Hello, the software will stop working when it opens under win7

**Comment by LazyZhu** [comment]
Check .NET Framework version on your win7, you need at least version 4.6.1 for TFT-Overlay working.

**Comment by Just2good** [comment]
Exactly what LazyZhu said 4.6.1 is required to launch the program [Link here](https://www.microsoft.com/en-us/download/details.aspx?id=49981)
