### ISSUE TITLE
Suggestion: Add item information in item builder

### ISSUE THREAD

**Issue by Phoenix616** [Just2good/TFT-Overlay#87]
Currently you have to remember what each item does or have to switch back to the individual items if you want to know the effect that all the combined items could have in the item builder.

Adding a small hover or alternatively a separate text field that displays the effect of the currently hovered item would be useful. (Or maybe even a list below the window with all items and their effects that can be build?)

**Comment by Just2good** [comment]
I might be able to add tooltips to them, I'll add them in once the thing I'm working on is done.
