### ISSUE TITLE
Suggestion: Add Damage Chart

### ISSUE THREAD

**Issue by Shrooblord** [Just2good/TFT-Overlay#88]
![image](https://user-images.githubusercontent.com/3255068/61708590-70ea4880-ad4d-11e9-8232-2795bf46d59e.png)

Hey there. Was wondering if you could add something akin to this to the program. Would help a lot in calculating in losses when planning your next move (eg. rolling with a loss streak; surviving until next Caroussel, etc.).

**Comment by Just2good** [comment]
I knew I forgot something thanks
