### ISSUE TITLE
Adding items on Main not working

### ISSUE THREAD

**Issue by seiftie** [Just2good/TFT-Overlay#91]
I'm not sure if I'm missing something here, but I was hoping the + and - buttons on the items in the **Main** group, would add an item in the **Item Builder** group.

This would speed up the process of using the Item Builder.

![image](https://user-images.githubusercontent.com/9054650/61856350-3fdf5480-aec2-11e9-9e24-99a1fa5560d3.png)

**Comment by Just2good** [comment]
Its only for design not interactable. They will do something soon though. (Still trying get the process down right)
