### ISSUE TITLE
OBS Studio can't capture overlay via window/game source.

### ISSUE THREAD

**Issue by Phoenix616** [Just2good/TFT-Overlay#93]
Currently there doesn't seem to be a way of capturing the overlay in OBS Studio (v23.2.1) with a window or game source. The window source will simply display a black screen and the game one nothing. (It's not a game so I guess that makes sense?)

Not sure what exactly is causing the black screen to show up without any of the elements showing (I already tried setting the render mode to software only in the overlay code as OBS seems to have had issues with hardware acceleration in the past but that didn't change anything)

**Comment by Just2good** [comment]
OBS can't render WPF programs with Nostyle/TransparentWindow on. Only work around is to do a Monitor/Full Window capture so that it just shows everything. Sadly this is one of the things that just cant be changed.

**Comment by Phoenix616** [comment]
Uh, interesting. I guess I'll go bug the OBS devs about it then. Thanks for
the info.
