### ISSUE TITLE
No software icon in the taskbar under the version 2.0.2

### ISSUE THREAD

**Issue by Wu-Zzz** [Just2good/TFT-Overlay#94]
There is no software icon on the taskbar, you can't  exit the software quickly, you need to end the process in Task Manager.

![Uploading 微信截图_20190728014018.png…]()

**Comment by Wu-Zzz** [comment]
![20190728014018](https://user-images.githubusercontent.com/18748508/61997764-44318a80-b0d9-11e9-805e-2dca543db7d9.png)

**Comment by Carrybag1** [comment]
+1, no way to close it except task mgr?

**Comment by Just2good** [comment]
I was also told this by another person on discord, still trying to figure out of its because of the fullscreen support that I added in the other day.
