### ISSUE TITLE
Weird Bug cases after game end to "Skip Waiting For Stats"

### ISSUE THREAD

**Issue by SpearRipper** [Just2good/TFT-Overlay#96]
IDK what's wrong with the tool after update

But for some weird reason when I run it always after I end up a game I don't get the game stats
instead, it always leads to " SKIP WAITING FOR STATS " message while I am unable to see the history of the match, and no matter how much of time I wait it never show stats and i had to click skip.
https://i.imgur.com/3QmuzfS.jpg
When I close the tool the stats show up normally

**Comment by Just2good** [comment]
Do you normally play on fullscreen? It might be from the fullscreen support that was added a few days ago.

**Comment by Just2good** [comment]
New update was added, let me know if you still get this issue.

**Comment by Just2good** [comment]
Didnt get this issue with new update, and no replies, going to close this. Feel free to reply back, I read all replies locked or not.
