### ISSUE TITLE
Google and Windows security activating on download

### ISSUE THREAD

**Issue by Schokostoffdioxid** [Just2good/TFT-Overlay#98]
Hey,
today i've discoverd that Google marks the release zip as uncommon
see: _https://support.google.com/chrome/answer/6261569?visit_p=ib_download_blocked_ for more Info.

Also when starting the exe in my case symantec is Alerting that the file might be Maleware and that it triggers a WS.Reputation.1 Alert.

Here is the Alert:
_https://www.symantec.com/security-center/writeup/2010-051308-1854-99_

I hope this helps.

**Comment by Just2good** [comment]
Definitely a false positive. [Virustotal](https://www.virustotal.com/gui/file/6c1bc2bf69e8858baa9048ae61f2ddc7baaa9cf59a112c6ec69f4b776e53fa75/detection)

You can even compile the source yourself and will still get the same issue.
